complete -c mmpd -f
complete -c mmpd -n "__fish_use_subcommand" -a "download" -d "Download non-interaktif"
complete -c mmpd -n "__fish_use_subcommand" -a "retrofit" -d "Perbaiki koleksi lama"
complete -c mmpd -n "__fish_use_subcommand" -a "lyrics" -d "Suntik terjemahan LRC"
complete -c mmpd -n "__fish_use_subcommand" -a "organize" -d "Rapikan audio + LRC"
complete -c mmpd -n "__fish_use_subcommand" -a "cache" -d "Kelola cache"
complete -c mmpd -n "__fish_use_subcommand" -a "config" -d "Kelola config.toml"
complete -c mmpd -n "__fish_use_subcommand" -a "doctor" -d "Diagnostik"
complete -c mmpd -n "__fish_use_subcommand" -a "self-update" -d "Update non-destruktif"
complete -c mmpd -n "__fish_use_subcommand" -a "completion" -d "Cetak skrip completion"
complete -c mmpd -s V -l version -d "Cetak versi"
complete -c mmpd -s q -l quiet -d "Kurangi output"
complete -c mmpd -n "__fish_seen_subcommand_from download" -s f -l format -a "mp3 flac wav best"
complete -c mmpd -n "__fish_seen_subcommand_from download" -l lyrics -a "musixmatch chain youtube-cc cc off none"
complete -c mmpd -n "__fish_seen_subcommand_from download retrofit lyrics" -l transliterate -a "auto ja zh yue off"
complete -c mmpd -n "__fish_seen_subcommand_from download retrofit lyrics" -l lrc-format -a "gabung pisah id_only"
complete -c mmpd -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
